# Generated by Django 2.0.2 on 2018-11-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('modifytime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='bookhead')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50, null=True)),
                ('press', models.CharField(max_length=50, null=True)),
                ('pubtime', models.DateField(null=True)),
                ('edition', models.IntegerField(null=True)),
                ('printtime', models.DateField(null=True)),
                ('impress', models.IntegerField(null=True)),
                ('isbn', models.CharField(db_column='ISBN', max_length=50, null=True)),
                ('words', models.CharField(max_length=50, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=20, null=True)),
                ('paper', models.CharField(max_length=20, null=True)),
                ('packaging', models.CharField(max_length=20, null=True)),
                ('addtime', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default=1, max_length=1)),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='Bookclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('modifytime', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 't_bookclass',
            },
        ),
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('dangprice', models.FloatField()),
                ('sellnumber', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('version', models.CharField(default=1, max_length=1)),
                ('editsupport', models.IntegerField(null=True)),
                ('book_infor', models.ForeignKey(db_column='book_infor', on_delete=django.db.models.deletion.CASCADE, to='indexapp.Book')),
            ],
            options={
                'db_table': 't_booklist',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('emal', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('regtime', models.DateTimeField(auto_now=True)),
                ('modifytime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('totalprice', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=20)),
                ('cell_phone', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('ordertime', models.DateTimeField(auto_now=True)),
                ('order_user', models.ForeignKey(db_column='order_user', on_delete=django.db.models.deletion.CASCADE, to='indexapp.MyUser')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('dangprice', models.FloatField()),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='indexapp.Book')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='indexapp.Order')),
            ],
            options={
                'db_table': 't_orderlist',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='class_id',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='indexapp.Bookclass'),
        ),
        migrations.AddField(
            model_name='address',
            name='user_address',
            field=models.ForeignKey(db_column='user_address', on_delete=django.db.models.deletion.CASCADE, to='indexapp.MyUser'),
        ),
    ]
