# Generated by Django 2.0.2 on 2018-11-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_auto_20181123_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(default='16', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='impress',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(db_column='ISBN', default='123454321', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='packaging',
            field=models.CharField(default='平装-胶订', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default='12345', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper',
            field=models.CharField(default='轻纸型', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='sellnumber',
            field=models.IntegerField(default=999),
        ),
    ]
